# config/train/pilotnet_baseline.yaml
name: pilotnet_baseline

train:
  loss: mse
  metrics: [mae]
  epochs: 1
  steps_per_epoch: 1000
  val_steps: 100

optim:
  type: adam
  lr: 0.001

callbacks:
  wandb:
    enabled: false
    project: pilotnet
  checkpoint:
    enabled: true
    monitor: val_loss
    save_best_only: true
    verbose: 1
  early_stopping:
    enabled: true
    monitor: val_loss
    patience: 10
    restore_best_weights: true
    verbose: 1